### ISSUE TITLE
Incorrect stack identification

### ISSUE THREAD

**Issue by ailrst** [UQ-PAC/bil-to-boogie-translator#100]
The tool can output stores to mem at addresses that are explicitly offsets from the stack pointer such as here 
https://github.com/UQ-PAC/bil-to-boogie-translator/pull/99

This may be improved by implementing stack identification based on the memory region analysis, or fixed in the prototype implementation of stack identification first.

**Comment by l-kent** [comment]
Can you give a proper example of this? I don't know where your example in #99 came from

**Comment by ailrst** [comment]
This is the same example; https://gist.github.com/ailrst/60133afbeda1aab9255752adee510553#file-example-bpl-L354

Or do you want me to find an instance in an existing example?

**Comment by l-kent** [comment]
That's fine, thanks.
