### ISSUE TITLE
Unreachable match in boogie translation

### ISSUE THREAD

**Issue by ailrst** [UQ-PAC/bil-to-boogie-translator#105]
Scala 3.3.1 is showing a warning on the boogie translation for LocalAssign statements which looks legitimate. 

```
[warn] -- [E030] Match case Unreachable Warning: /home/am/Documents/programming/2023/bil-to-boogie-translator/src/main/scala/translating/IRToBoogie.scala:468:49 
[warn] 468 |      val loads = rhs.functionOps.collect { case m: BMemoryLoad => m }
[warn]     |                                                 ^^^^^^^^^^^^^^
[warn]     |                                                 Unreachable case
[warn] -- [E030] Match case Unreachable Warning: /home/am/Documents/programming/2023/bil-to-boogie-translator/src/main/scala/translating/IRToBoogie.scala:472:57 
[warn] 472 |        val gammas = rhsGamma.functionOps.collect { case g: GammaLoad => g.gammaMap }.toSeq.sorted
[warn]     |                                                         ^^^^^^^^^^^^
[warn]     |                                                      Unreachable case
[warn] two warnings found
```

This can be seen by compiling on the branch `update-scala`.

`functionOps` is a `Set[FunctionOp]`, which `GammaLoad` and `BMemoryLoad` aren't subclasses of.

The relevant code snippet is below; I believe this means rely() checks for memory accesses occurring in the RHS of a local assign won't be inserted? 

```
      val loads = rhs.functionOps.collect { case m: BMemoryLoad => m }
      if (loads.isEmpty || loads.forall(_.memory == stack)) {
        List(assign)
      } else {
        val gammas = rhsGamma.functionOps.collect { case g: GammaLoad => g.gammaMap }.toSeq.sorted
        val memories = loads.map(m => m.memory).toSeq.sorted
        List(ProcedureCall("rely", Seq(), Seq(), memories ++ gammas), assign)
      }
```

I could fix this by adding corresponding BMemoryLoad.memory and GammaLoad.gammaMap to MemoryLoadOp and GammaLoadOp but that seems superficial. 

I'm not sure why this needs a different approach to MemoryStore, this function seems to have the implicit assumption you don't store and load in the same statement; e.g. `MemoryStore`s to the stack don't check whether the RHS contains a global load.

**Comment by l-kent** [comment]
Ah I had noticed there may be an issue around missing relies on Friday but hadn't investigated yet, thanks for finding it for me.

The code snippet checks if a LocalAssign (assignment to temporary variable/register) contains no loads or they are all stack loads (realistically there should only be one load per statement) because if so then a rely is not needed, otherwise a rely should be added before the load.
