### ISSUE TITLE
Type mismatch lifted lattice

### ISSUE THREAD

**Issue by yousifpatti** [UQ-PAC/bil-to-boogie-translator#113]
I have tried to add the lifted (extra bottom) lattice solver, however, a type mismatch occurs in `RunUtils.scala`
A type mismatch Error: 
`[error] 155 |    val mraResult: Map[CfgNode, Set[MemoryRegion]] = mraSolver.analyze(true)`
`[error]     |                                                     ^^^^^^^^^^^^^^^^^^^^^^^`
Found: mraSolver.lattice.Element 
Required: Map[analysis.CfgNode, Set[analysis.MemoryRegion]]`

This implementation addresses: #39 

Related PR Code: #114

**Comment by l-kent** [comment]
You changed the lattice that the mraSolver uses, so you need to change the type declaration too. 

Map[CfgNode, mraSolver.liftedstatelattice.Element] should work, but I'm not sure if it's possible to get anything more precise than that. The types used by these TIP lattices are a horrible mess.
