### ISSUE TITLE
Missing types & elements in StatementLoader

### ISSUE THREAD

**Issue by andrewj-brown** [UQ-PAC/bil-to-boogie-translator#20]
Not found: type SecLatticeElemContext (line 245) and nothing in astnodes/sec/SecLatice.scala that matches either.

BilParser.BilParser.GammaContext and BilParser.BilParser.LpredContext are missing members (ID and secExpr, respectively).

I suspect some changes made to the .g4 files were compiled into the Antlr .jar file, but the compiled changes weren't committed.

**Comment by andrewj-brown** [comment]
Sorry not sorry to bug you Tom but this relates to your security lattice changes, so you're up...

**Comment by TomCranitch** [comment]
`SecLatticeElemContext` should be generated by bil (specifically from https://github.com/UQ-PAC/bil-to-boogie-translator/blob/e07c4b85c12b8c85a8a0bab8d83ac00ff2e85074/src/main/antlr4/Bil.g4#L136). If it's not being generated you could try deleting the `target/managed_src` folder to force it to rebuild those files and hopefully it will work. If not let me know and I can try and have a closer look 

This was a somewhat last minute change last week when I added support for a general security lattice, so something might also be out of wack. 

The issues with GammaContext and LpredContext, would have also happened when I made those changes. Based on the antlr grammar, both of these class should in theory have those member variables

**Comment by andrewj-brown** [comment]
had to delete basically everything that's not in the repo, but something worked...
