### ISSUE TITLE
Update GTIRB loader to simplify BLR handling

### ISSUE THREAD

**Issue by ailrst** [UQ-PAC/bil-to-boogie-translator#207]
The BLR bug has been fixed upstream in ddisasm now, so we can remove the code handling conditionals in the middle of blocks hopefully. The nix package has the new version of ddisasm. 

Currently it seems like trying to use gts files from the new version hit the unimplemented cases in the control flow reconstruction for indirect conditions.

Somewhat related to this; https://github.com/UQ-PAC/bil-to-boogie-translator/issues/183

**Comment by l-kent** [comment]
Fixed in #197
