### ISSUE TITLE
Refactor: combine multiple versions of eval() into one if possible.

### ISSUE THREAD

**Issue by utting** [UQ-PAC/bil-to-boogie-translator#35]
During a code review we noticed that there are several classes (interpreter, const prop, etc.) where eval is defined to evaluate all the various bitvector operators.  

Can we reduce the code duplication by moving these to a common base class or calling a library method?

**Comment by l-kent** [comment]
Is this still an issue with the updated constant propagation? That was where the issue was, I believe

**Comment by yousifpatti** [comment]
All analyses use the `evaluateExpression()` in `UtilMethods.scala`

The interpreter eval method is different as it does not only have additional cases but the interpreter works on the IR Program and not the CFG so the results of the constant propagation cannot be used without a major rewrite of the interpreter and adding an option for custom cases in the `evaluateExpression()`

An example modification to `evaluateExpression()` function declaration:
```
def evaluateExpression(exp: Expr, constantPropResult: Map[Variable, FlatElement[BitVecLiteral]], customCases: Expr => Option[BitVecLiteral] = _ => None): Option[BitVecLiteral] 
```



And modify `eval()` in the `Interpreter.scala`:
```
  def eval(exp: Expr, n: CfgNode): BitVecLiteral = {
    val customCases: Expr => Option[BitVecLiteral] = {
      case m: Memory =>
        Logger.debug(s"\t$m")
        ???

      case ml: MemoryLoad =>
        Logger.debug(s"\t$ml")
        val index: Int = eval(ml.index).value.toInt
        Some(getMemory(index, ml.size, ml.endian, mems))

      case ms: MemoryStore =>
        val index: Int = eval(ms.index).value.toInt
        val value: BitVecLiteral = eval(ms.value)
        Logger.debug(s"\tMemoryStore(mem:${ms.mem}, index:0x${index.toHexString}, value:0x${
          value.value
            .toString(16)
        }[u${value.size}], size:${ms.size})")
        Some(setMemory(index, ms.size, ms.endian, value, mems))

      case _ => None
    }
    evaluateExpression(exp, constantProp(n), customCases).getOrElse(???)
  }
```

**Comment by l-kent** [comment]
I'm happy to close this. I think the concern was just about the lattice having to define operations for each bitvector operator, but that is how the lattice setup works, it isn't really something that can be generalised to the interpreter or anything.
