### ISSUE TITLE
Refactor: investigate use of worklist in SimpleMonotonicSolver

### ISSUE THREAD

**Issue by utting** [UQ-PAC/bil-to-boogie-translator#39]
SimpleMonotonicSolver in MonotonicSolver.scala is currently doing several recursive traversals of each graph and returning from a node on the second or greater pass when its value does not change.  This could potentially be less efficient than a worklist approach, and could stop short of the true fix point if there are longer chains of dependencies.

Investigate using a worklist algorithm, but also check how to ensure that every node in a procedure is visited at least once.

**Comment by yousifpatti** [comment]
Reasons behind the monotonic solver:
Context switching: Because the VSA analysis uses stack context switching, it relies on the order of function entry/exit nodes. Therefore, solver needs to maintain a monotonic approach in traversing the CFG as opposed to all CFG nodes being added.

**Comment by l-kent** [comment]
What's the status of this? I think a suitable approach to this would be to port over the WorklistWithReachability (I think that's what it's called) from TIP?

**Comment by yousifpatti** [comment]
Has been marged into main. Refer to PR: #114
