### ISSUE TITLE
Bug in IR to CFG Jumps Processing

### ISSUE THREAD

**Issue by yousifpatti** [UQ-PAC/bil-to-boogie-translator#56]
Currently, when converting an IR to a CFG there is a bug in processing Jumps.

For example:
If a block has multiple jumps, then it will only generate the first jump and skip the others. This is because visitJumps in CFG.scala takes "jmps" list but only process "jmps.head".

There needs to be a recursive call/looping mechanism to process the other jumps and append them to the CFG.

Have a look at this example: 
run examples/functionpointer/functionpointer_clang.adt examples/functionpointer/functionpointer_clang.relf -analyse

After VSA, the new resolvedCFG contains three calls for R8 at block 000004fd but only the first one gets processed.

**Comment by ailrst** [comment]
> There needs to be a recursive call/looping mechanism to process the other jumps and append them to the CFG.

Rather than a loop in RunUtil.scala we will replace IndirectCalls that can resolve to multiple possible direct calls, with conditional branches on the indirect call address which go to DirectCalls and return to the same cfgnode, maintaining the status quo of only one or two calls per block.
