### ISSUE TITLE
Missing intra succ and pred edges from inter CFG

### ISSUE THREAD

**Issue by yousifpatti** [UQ-PAC/bil-to-boogie-translator#60]
In the CFG there are four functions that add edges to the CFG.
addInlineEdge
addInterprocCallEdge
addIntraprocEdge
addRegularEdge

However, when the Interproc edges are needed [i.e. succ(intra=false)] only the Interproc edges are returned.
This results in an issue as we lose track of the Intraproc edges and as such there is no way to traverse graphs' statements.

The add Edge methods need to be investigated and some modified to add their Intraproc edges to the succInter/predInter class variables.

**Comment by l-kent** [comment]
This was completed, wasn't it? @yousifpatti @ailrst

**Comment by yousifpatti** [comment]
@l-kent This has been addressed. I will close the issue.
