### ISSUE TITLE
Emitting invalid comparisons

### ISSUE THREAD

**Issue by ailrst** [UQ-PAC/bil-to-boogie-translator#84]
This example https://github.com/UQ-PAC/bil-to-boogie-translator/tree/mini-cntlm-example/examples/simplified_http_parse_basic

Fails to verify in boogie (without a spec) due to the following appearing with boogie version 3.0.4.0

```
boogie_out.bpl(370,4): Error: mismatched types in assignment command (cannot assign bv32 to bv64)
boogie_out.bpl(378,4): Error: mismatched types in assignment command (cannot assign bv32 to bv64)
```

**Comment by ncough** [comment]
Any chance you have lifted using the Primus Lisp definitions for BAP, rather than the ASLp plugin? The general style of the ADT seems to suggest that might be the case. Mismatched types were one of the issues with the Primus Lisp version.

**Comment by l-kent** [comment]
Yeah, it seems to be an issue with the BAP version - it's failing to lift part of the instructions `cset w0, ne`, `ldr w0, [sp, #0x6c]` and `ldrb w0, [x0]` correctly and produces multiple assignments with mismatching sizes - it should be padding the 32-bit values it assigns to the 64-bit registers. You can see this at %00000f92, %00000faa, %00000ed3 and %00000f04 in the ADT file.

**Comment by ailrst** [comment]
Yes that's what's happening, thanks
