### ISSUE TITLE
Reference to initial 'main' procedure node in ProgramCfg class

### ISSUE THREAD

**Issue by l-kent** [UQ-PAC/bil-to-boogie-translator#95]
It would be very useful to have a reference to the initially called 'main' procedure of a program as a variable in the ProgramCfg class. Such a reference already exists in the Program class, but making use of this in relation to the ProgramCfg requires traversing all procedure nodes in the CFG to find the matching CFG node.

This is especially important as the initially called procedure isn't always named "main" - this can vary as the compiler may optimise out the function named main, for instance.

**Comment by ziggyfish** [comment]
merge request #76 has a fix for this.
